In [1]:
!pip install tensorflow

In [12]:
import tensorflow as tf

In [20]:
# 0D tensor
tensor_zero_d = tf.constant(1)
print("0D :", tensor_zero_d, "\n")
# 1D tensor
tensor_one_d = tf.constant(1,2,3)
print("1D :", tensor_one_d, "\n")
# 2D tensor
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("2D :", tensor_two_d, "\n")
# 3D tensor
tensor_three_d = tf.constant([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[10,11,12],
     [13,14,15],
     [16,17,18]],
    
    [[19,20,21],
     [22,23,24],
     [25,26,27]]
])
print("3D :", tensor_three_d, "\n")
# 4D tensor
tensor_four_d = tf.constant([
    [[[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[10,11,12],
     [13,14,15],
     [16,17,18]],
    
    [[19,20,21],
     [22,23,24],
     [25,26,27]]
],
    [[[28,29,30],
    [31,32,33],
    [34,35,36]],
    
    [[37,38,39],
     [40,41,42],
     [43,44,45]],
    
    [[46,47,48],
     [49,50,51],
     [52,53,54]]
],
    [[[55,56,57],
    [58,59,60],
    [61,62,63]],
    
    [[64,65,66],
     [67,68,69],
     [70,71,72]],
    
    [[73,74,75],
     [76,77,78],
     [79,80,81]]]
])
print("4D :", tensor_four_d, "\n")

0D : tf.Tensor(1, shape=(), dtype=int32) 

1D : tf.Tensor([1. 1. 1.], shape=(3,), dtype=float64) 

2D : tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32) 

3D : tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]], shape=(3, 3, 3), dtype=int32) 

4D : tf.Tensor(
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]
   [ 7.  8.  9.]]

  [[10. 11. 12.]
   [13. 14. 15.]
   [16. 17. 18.]]

  [[19. 20. 21.]
   [22. 23. 24.]
   [25. 26. 27.]]]


 [[[28. 29. 30.]
   [31. 32. 33.]
   [34. 35. 36.]]

  [[37. 38. 39.]
   [40. 41. 42.]
   [43. 44. 45.]]

  [[46. 47. 48.]
   [49. 50. 51.]
   [52. 53. 54.]]]


 [[[55. 56. 57.]
   [58. 59. 60.]
   [61. 62. 63.]]

  [[64. 65. 66.]
   [67. 68. 69.]
   [70. 71. 72.]]

  [[73. 74. 75.]
   [76. 77. 78.]
   [79. 80. 81.]]]], shape=(3, 3, 3, 3), dtype=float32) 



In [21]:
print(tensor_zero_d.shape)
print(tensor_one_d.shape)
print(tensor_two_d.shape)
print(tensor_three_d.shape)
print(tensor_four_d.shape)

()
(3,)
(3, 3)
(3, 3, 3)
(3, 3, 3, 3)


> [!note] You can reduce the memory space taken by tensor data by defining the data type to be processed and output as a different data type. <br> 
**Examples:**<br>
>- `int` (64, 32, 16, 8)
>- `float` (64, 32, 16, 8)
>- `double` (64, 32, 16, 8)

>Code Example:
>```python
>import tensorflow as tf
>
>tensor_three_d = tf.constant([
>    [[1, 2, 3],
>    [4, 5, 6],
>    [7, 8, 9]],
>    
>    [[10, 11, 12],
>     [13, 14, 15],
>     [16, 17, 18]],
>    
>    [[19, 20, 21],
>     [22, 23, 24],
>     [25, 26, 27]]
>], dtype=tf.float16)
>print("3D Tensor:", tensor_three_d)
>```
><br>
>This keeps the output of the data the same while taking up less space. Note that the chosen data type should be able to contain the data processed; otherwise, the processed data will be inaccurate.

In [33]:
import tensorflow as tf

# Generate a random tensor with shape (2, 3) from a normal distribution with mean 0 and standard deviation 1
# Set the random seed for reproducibility
tf.random.set_seed(42)

random_tensor = tf.random.normal(
	shape=(2, 3), 
	mean=0.0, 
	stddev=1.0, 
	seed=42, 
	dtype=tf.float32, 
	name="my_random_tensor")

# Print the random normal tensor
print(random_tensor)

tf.Tensor(
[[ 1.3148774  -0.15421568  0.9113878 ]
 [-0.7991441  -0.10875294  0.28436786]], shape=(2, 3), dtype=float32)
